// @generated by s3admin-cloud-setup - do not edit
export { default } from "@s3administrator/cloud/marketing/pages/self-hosted"
export { metadata } from "@s3administrator/cloud/marketing/pages/self-hosted"
