// @generated by s3admin-cloud-setup - do not edit
export { default } from "@s3administrator/cloud/marketing/pages/security"
export { metadata } from "@s3administrator/cloud/marketing/pages/security"
